name: Rodrigo Baron
description: Software Developer
meta_description: "Rodrigo Baron, Blogging about programmable things.. and other stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://rodrigobaron.com'
#google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'rodrigobaron'

# Details for the RSS feed generator
url:            'http://rodrigobaron.com'
author:         'Rodrigo Baron'
authorTwitter:  'rodrigobaron_'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
